[package]
name = "test_example"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "native"
path = "src/lib.rs"


[package.metadata.vcpkg]
git = "https://github.com/microsoft/vcpkg"
rev = "4c1db68"
dependencies = ["sdl3"]


[dependencies]
realgameengine ={ "path" = "../.." ,features = [
    #"debug_log",
    ]}

