[package]
name = "test_example"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "native"
path = "src/lib.rs"


[dependencies]
console_error_panic_hook = "0.1.7"
realgameengine ={ "path" = "../.." }
wasm_thread = "0.3.3"


[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"


[package.metadata.wasm-pack.profile.release]
wasm-opt = false