[build]
target = "wasm32-unknown-unknown"

[target.wasm32-unknown-unknown]
rustflags = [
    "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
    "-C", "link-arg=--import-memory",          # <-- BU ÇOK ÖNEMLİ (Belleği dışarıdan al)
    "-C", "link-arg=--export-memory",          # (Opsiyonel ama bazen gereklidir)
    "-C", "link-arg=--max-memory=4294967296"   # <-- JS'deki 'maximum' ile aynı olmalı
]

[unstable]
build-std = ["std", "panic_abort"]